name: qrscan_plus
description: A Plug-in for dart, which help you scanning and Generating barcode and qrcode with Android and IOS Device.
version: 1.0.4+1
homepage: https://github.com/itxmubi/qrscan_plus
repository: https://github.com/itxmubi/qrscan_plus
issue_tracker: https://github.com/itxmubi/qrscan_plus/issues
documentation: https://github.com/itxmubi/qrscan_plus#readme

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.14.2

flutter:
  plugin:
    platforms:
      android:
        package: com.shinow.qrscan
        pluginClass: QrscanPlugin
      ios:
        pluginClass: SwiftQrscanPlugin
